name: Build Web Only

on:
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest # Runner padrão x86_64 rápido e gratuito

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Instalar dependências da Web
        run: yarn install --frozen-lockfile

      - name: Compilar interface Web
        run: yarn web build

      - name: Upload da pasta dist
        uses: actions/upload-artifact@v4
        with:
          name: stump-web-dist
          path: web/dist/
          retention-days: 7